//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Orbital7.MyGames.Scraping.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Orbital7.MyGames.Scraping.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ;******************************************************************************
        ///;* PUGSY&apos;S CHEATS Release Date: 18 MAY 2000 (Base release for MAME 0.36Final) *
        ///;*          Also includes cheats for MAME 0.37 BETA 1 and 2                   *
        ///;*  Cheat File *FULLY* compatible with *ALL* MAME versions mentioned above    *
        ///;*                                                                            *
        ///;*  This CHEAT.DAT file was downloaded from Pugsy&apos;s MAME Cheat Page at:-      *
        ///;*                        http:/ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string cheat_dat {
            get {
                return ResourceManager.GetString("cheat_dat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This list contains all games supported by FB Alpha.
        ///
        ///8363 games supported in total; X = excluded from build; D = included in debug build only; NW = not working
        ///
        ///  name		  status  full name						  parent	  year	  company	  hardware	  remarks
        ///+---------------+-------+-------------------------------------------------------+---------------+-------+---------------+---------------+---------------------------------------+
        ///| 8ballact	|   NW	| &quot;8ballact&quot;						| 		| 1984	| Miscellaneous	| 		| Seatongrove Ltd (M [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string gamelist {
            get {
                return ResourceManager.GetString("gamelist", resourceCulture);
            }
        }
    }
}
